### ISSUE TITLE
Update Access Rights Guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#10]
- https://uhlibraries-digital.github.io/bcdams-map/#accessRights
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/accessRights

**Comment by librarycard** [comment]
I don't think this needs to be a human-readable field, the DAMS just needs to authenticate users and display (or not display) items accordingly (i.e. if a person is accessing items from an on-campus IP range, or if a person is logged in as a library employee)

**Comment by seanlw** [comment]
@librarycard I think this still needs to be human-readable. If the user is blocked it's important to describe what access right prevented them from viewing the object. I for one would love to get away from the generic 'Access Denied' text. I can also see it being important long term as objects move from one system to another, or simply displayed in different systems. Something like Spotlight for instance.

**Comment by metaweidner** [comment]
Either way we'll need to define access levels and develop a corresponding local vocabulary.

**Comment by metaweidner** [comment]
@librarycard @amgaynor The Access Rights guidelines page could also use a little more information. It will be a work in progress until we have some experience with Hyku.

**Comment by amgaynor** [comment]
@metaweidner @librarycard I've updated the page with our current info. Should I close this issue for now or do you want me to leave it open as we wait to see what happens with Hyku?

**Comment by metaweidner** [comment]
Thanks @amgaynor. The info you added will look better as a table rather than two bulleted lists. I'll make that change and close out this issue. Let's try to clear the board by the end of this sprint.

**Comment by metaweidner** [comment]
@amgaynor closed accessRights guidelines with c8af95d71aa4ad501a8d42f237cdd326d6b51f68
