### ISSUE TITLE
Update Title guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#11]
- https://uhlibraries-digital.github.io/bcdams-map/#title
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/title

**Comment by amgaynor** [comment]
Can identical titles be used for different objects? E.g. "Agreement and contract." 
Should we add a date at the end to distinguish items when possible? What if it's the same date? 
See: http://digital.lib.uh.edu/collection/hnh/item/128, http://digital.lib.uh.edu/collection/hnh/item/465

**Comment by amgaynor** [comment]
We will not create file-level titles for multipage works. :smiley:

**Comment by metaweidner** [comment]
Ensuring the uniqueness of titles in a collection seems like an unnecessary burden on metadata creators. If I remember correctly, the argument for doing this has been that unique titles ensure unique citations when researchers use UHDL objects in their work. The addition of persistent ARK identifiers to our workflow should eliminate that requirement. That said, input rules outlining how to include contextual information such as dates might be desirable.

**Comment by amgaynor** [comment]
Work titles do not have to be unique.

**Comment by amgaynor** [comment]
For letter titles: Letter from [Name] to [Name], YYYY Month DD
Supply date only if there is a date.
(No longer include "regarding" statement in title)

**Comment by amgaynor** [comment]
How should we format title for newsletters? Currently Vol and No. in Description field. We would like to move that information into the Title field.

**Comment by metaweidner** [comment]
Add in Preservation / Access headings

**Comment by amgaynor** [comment]
Updated title guidelines. Added Preservation/Access headings: https://uhlibraries-digital.github.io/bcdams-map/guidelines/title

**Comment by amgaynor** [comment]
@librarycard feel free to update the Preservation guidelines for this.

**Comment by amgaynor** [comment]
@librarycard When you've completed the Preservation guidelines, feel free to close this issue.
