### ISSUE TITLE
Update Date guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#13]
- https://uhlibraries-digital.github.io/bcdams-map/#date
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/date

**Comment by amgaynor** [comment]
Will this be a single field from now on? vs. One field that's human readable and one field that's machine readable? What if the date cannot be expressed well in EDTF (e.g. College of Architecture posters - @christinz I think there was another collection - could you post here?)

**Comment by amgaynor** [comment]
If we choose to go with one date field formatted in EDTF, would we be able to display it in a human readable form a la UNT? https://digital.library.unt.edu/help/guide/dates/

**Comment by metaweidner** [comment]
@amgaynor Long term: yes, there are tools that will do that for us: http://blogs.library.duke.edu/bitstreams/2016/04/22/edtf-humanize/ Short term: remains to be seen what Hybox gives us out of the gate

**Comment by amgaynor** [comment]
We need to confirm the natural language expression of dates in EDTF:

EDTF | Natural language
------|---------
1975-07-01  | January 1, 1975
1945? | 1945?
1981~ | approximately 1981
1975-23 | Autumn 1975 (or do we want Fall 1975?)
197x | 1970s
19xx | 1900s (in humanized EDTF, we will not have 20th century)
1981/1985 | 1981-1985 (other option would be 1981 to 1985. This form is not currently used in UHDL)
[1888, 1889, 1891] | 1888, 1889 or 1891 (I've never/rarely seen this in our collection)

@dulekde @christinz  Are there other types of dates you've see in UHDL that need to be addressed?

**Comment by seanlw** [comment]
There is also this available:

EDTF | Natural language
------| -------------
{1888, 1889, 1891} | 1888, 1889 and 1891

**Comment by christinz** [comment]
1975-23, We have used "Fall" in a few collections in the past.

**Comment by dulekde** [comment]
"u" is being used
http://digital.lib.uh.edu/collection/p15195coll34/item/108 July 28, 18??; 18uu-07-28
http://digital.lib.uh.edu/collection/1984_003/item/867 March 19 - March 21; 19uu-03-19/19uu-03-21

**Comment by amgaynor** [comment]
Approximate date ranges, e.g.  "approximately 1970-1980". What's the correct way to enter this? 1970~/1980~? I think the more literal translation of this would be "approximately 1970-approximately 1980", but that's not in the UHDL.

**Comment by amgaynor** [comment]
In bibliographic (and archival?) practice, brackets meant that the value is supplied. Do we want to follow this practice?

**Update:** We won't use brackets to indicate supplied dates. This practice has been discontinued in archives. For MARC records that include date in brackets, we will remove the brackets. 

**Update:** Brackets will be used per the EDTF standard to indicate a list of "or" dates when appropriate.

**Comment by amgaynor** [comment]
Old | New
----|-----
circa | approximately
Autumn | Fall
1920 to 1925 | 1920-1925
19XX | 1900s

**Comment by metaweidner** [comment]
@librarycard It looks like the Date field needs Preservation guidelines.
