### ISSUE TITLE
Update Publisher guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#15]
- https://uhlibraries-digital.github.io/bcdams-map/#publisher
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/publisher

**Comment by amgaynor** [comment]
I think this needs to be reviewed as we talk about the Place of Creation field. In most cases the Place of Creation field is the location of the publisher, normally reflected in the MARC record as, e.g., London: Schott & Comp.; Leipzig: C.F. Leede. Where will we put that geographic element (if anywhere)? Will we include it in this field?

**Comment by metaweidner** [comment]
Agreed. Probably best to hold off on finalizing this until we see what capabilities we have for defining metadata in the system.

**Comment by amgaynor** [comment]
We decided that at least in the short term, we will put the location of the publisher in the Place field. Ideally the location of the publisher would be related to the publisher record in Cedar.
