### ISSUE TITLE
Update Collection Guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#16]
- https://uhlibraries-digital.github.io/bcdams-map/#isPartOf
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/isPartOf

**Comment by amgaynor** [comment]
We will use the original collection title, and not use digital collection title.

**Comment by amgaynor** [comment]
We can create landing pages for digital collections rather than capture this info in a metadata field.

**Comment by metaweidner** [comment]
What about digital collections made up of multiple provenance collections? It seems to me that there should be a place for these curated collections in the metadata. A landing page alone may not serve some users needs.

**Comment by amgaynor** [comment]
Entries for Collections will be created in [Cedar](https://vocab.lib.uh.edu/en/concepts/collection.html). Collections can represent repository, provenance collection, or digital collection.
