### ISSUE TITLE
Boolean values in map should be boolean data type not string

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/bcdams-map#18]
Fields within the map that have a true/false value shouldn't have "" around them.

Example:

Current:

{
label: "Title",
namespace: "dcterms",
name: "title",
uri: "https://uhlibraries-digital.github.io/bcdams-map/#title",
same_as: "http://purl.org/dc/terms/title",
definition: "A name given to the resource.",
range_label: "String",
required: "true",
repeatable: "false",
hidden: "false"
}

Should be:

{
label: "Title",
namespace: "dcterms",
name: "title",
uri: "https://uhlibraries-digital.github.io/bcdams-map/#title",
same_as: "http://purl.org/dc/terms/title",
definition: "A name given to the resource.",
range_label: "String",
required: true,
repeatable: false,
hidden: false
}

**Comment by metaweidner** [comment]
Closed with acc9cd727cd77f477cc62bda8fd8c1148e6fc059
