### ISSUE TITLE
Add guidelines attribute

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/bcdams-map#20]
The URI to the guidelines

**Comment by metaweidner** [comment]
completed with 5a26b3f229d7d079e42e2afbdbd5cc1aff15f1a3

**Comment by seanlw** [comment]
To be consistent with other uri fields, it should be labeled as `guidelines_uri`

**Comment by metaweidner** [comment]
closed with 554e4b17d5beb64e48b8ebd197792979f2ffd989
