### ISSUE TITLE
Add dcterms.identifier

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/bcdams-map#24]

**Comment by metaweidner** [comment]
@seanlw Wondering what to do with these:
- range: Should this be limited to an ARK URI? Or might it be just the ARK stem? The DPLA MAP lists this as a literal value. Could possibly be a call number, etc...
- obligation: every resource should have an ARK ID, but making this Required could cause validation problems during production
- repeatable: i can see a case for having multiple identifiers associated with a resource (call number, ARK, ASpace Digital Object URI, etc.)

**Comment by seanlw** [comment]
@metaweidner I don't think the range should be limited to the ARK URI. It makes since to have it contain multiple identifiers, the ARK only being one of them. For obligation what about requiredWhenAvailable? Our applications will be putting in the ARK, but I think that if other identifiers are available, they should be used. Which would also make this field repeatable. Thoughts?

**Comment by metaweidner** [comment]
@seanlw I've entered the range as 'String' for now. We can address the types of values the field will take when tackling #26. It's repeatable with a 'requiredWhenAvailable' obligation.

Closed with 94a397a26ff6ec2f349a76ab8d48c3010e3ad74a

**Comment by seanlw** [comment]
@metaweidner This should be added to the new Archival API endpoint as well.

**Comment by metaweidner** [comment]
added to archival api endpoint with d736b84ac486e9fe48218d5c30562632af70d487
