### ISSUE TITLE
Combine range_label and range_uri into array

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#26]
@seanlw Does this look right?

"range":
[
 { "label": "value", "uri":"value"},
 { "label": "value"}
]

**Comment by seanlw** [comment]
@metaweidner looks great!

**Comment by metaweidner** [comment]
@seanlw Thanks! As discussed, I'll hold off on this until we've had a chance to meet with the Metadata team.

**Comment by metaweidner** [comment]
Add `values` attribute for drop downs to `range` #25

**Comment by metaweidner** [comment]
@seanlw the bcdams-map api reflects the changes to the `range` data model. will this work?

**Comment by seanlw** [comment]
Works perfectly. Brays has been updated to reflect this new feature.
