### ISSUE TITLE
Add archival endpoint to API

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#27]
to be used for validating Archivematica SIP output from Carpenters

**Comment by metaweidner** [comment]
closed with 775c7a3befffab954f2b7b7ddd7a99500a64bc8b

**Comment by librarycard** [comment]
@metaweidner -- DPTF is using collection-level data to populate these fields, so mapping them to ASpace will be different for DPTF purposes vs. the DAMS. Is this a problem for using the BCDAMS map to validate in Carpenters and Brays?

**Comment by metaweidner** [comment]
@librarycard The DPTF use case should not pose any problems for validation against the MAP with Carpenters. We're using the MAP to mint local URIs for predicates, most of them linked to established vocabularies plus a few of our own. The predicates already minted are reusable in the preservation context, although the Guidelines documentation may need to be expanded to incorporate DPTF usage. Do you see a need for any preservation/Carpenters-specific predicates in the MAP?

**Comment by metaweidner** [comment]
@seanlw Is there any need to revisit the archival endpoint in the MAP at this time, or can this issue be closed?

**Comment by seanlw** [comment]
@metaweidner I think this issue can be closed.

**Comment by metaweidner** [comment]
TY @seanlw
