### ISSUE TITLE
Object in context

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#28]
In our meeting last week we talked about how it is important to convey that what the user sees in the repository may not be the entirety of the collection - i.e. only a series or some subset of the collection was digitized. I'm not sure that this would be best captured in a descriptive metadata field, but I wonder if we can use the ASpace uri to link out to the "Item in Context" that would take the user into Halls to see the finding aid.

**Comment by librarycard** [comment]
"Show item in context" would be great -- we will need to see if that type of view/link to finding aid will be possible with ASpace and its search function. Having the ASpace URI for each item seems like a good starting point, though?

**Comment by metaweidner** [comment]
@seanlw How should we approach the linkage between repository and archival context in Halls?

**Comment by seanlw** [comment]
I think having the ASpace URI in the repository would be the way to go. We could create a gem that is used within HyBox, theoretically, that could pull that information out of ASpace and either display it within the repository, or just link out into Halls. I'll need more information as to how you want the "Show item in context" to work and what information you need displayed to satisfy that feature.

At the very least we could start with just having a link in the repository to Halls and work our way up to the above.

**Comment by metaweidner** [comment]
Transferred to Trello.
