### ISSUE TITLE
Transcript & Translations

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#29]
Where will the current transcript field be mapped to? How will transcripts work in the new system? Also, where would we put translation of transcript?

**Comment by metaweidner** [comment]
Examples of translations from @lisacruces 
- Arizona: http://speccoll.library.arizona.edu/online-exhibits/exhibits/show/documented-border/item/234
- Bexar Archives: http://www.cah.utexas.edu/projects/bexar/docs.php?type=c
- Qajar: http://www.qajarwomen.org/en/items/15159A2.html

**Comment by amgaynor** [comment]
@lisacruces This is an example from Europeana: http://www.europeana.eu/portal/en/record/90402/SK_C_95.html

It's not entirely related to this conversation because it doesn't have a caption or anything, but if you look at the Classifications and the Format property you can see that they change (most of the time) when you change the language (upper right hand corner)

I'm pretty sure that this is generated on the fly using language tags that exist in the thesaurus metadata.

Also, I didn't read this yet, but this looks interesting:
Best Practices for Multilingual Access to Digital Libraries, White paper from Europeana: http://pro.europeana.eu/publication/best-practices-for-multilingual-access

**Comment by metaweidner** [comment]
Transferred to Trello.
