### ISSUE TITLE
Update Series Title Guidelines

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#32]
@librarycard @christinz @rmrichardson @lisacruces 

In our last meeting we talked about keeping the Series Title field. In my notes I have that we wanted to make sure to define in the input guidelines that this is not to be confused with the archival concept of series. I ran a report just to see where it was currently being used: 

https://docs.google.com/spreadsheets/d/18FbGH7jZMjF84_KGYU0e9JT3-Q4AraNPWLTtRy_js4M/edit?usp=sharing

Interestingly, it's mostly used in the UH photographs collection. I'm not sure exactly what the value in this field is coming from, though...it looks like it may be made up just to group things together?

If we are going to use this field for, say, book or video/show series titles, we'll have to clean up the UH photos.

**Comment by metaweidner** [comment]
@amgaynor What are the UHDL digital collections that make use of the Series field?

**Comment by amgaynor** [comment]
@metaweidner the UHDL collections that make use of Series: 

- KUHT Highlights (Values indicate TV series)
- Selections from the Franzheim Rare Books Room (Values indicate book series)
- Sheet Music of Flute and Violin Duets, 1790s-1850s (Series title of some kind; need more info from a specialist)
- University of Houston Campus Life*
- University of Houston People*

*These don't seem to be series; these look like folder titles: http://archon.lib.uh.edu/index.php?p=collections/findingaid&id=58&q=

**Comment by metaweidner** [comment]
Thank you @amgaynor. Copying over your question on bf:series from #50 

> Should the bf:series property be bf:hasSeries? I don't see bf:series in the BIBFRAME 2.0 Vocab List.

http://id.loc.gov/ontologies/bibframe.html#p_hasSeries
http://id.loc.gov/ontologies/bibframe.html

**Comment by rmrichardson** [comment]
I can confirm that UH Campus Life and UH People aren't Series, in either the archival or bf sense of the term.

**Comment by metaweidner** [comment]
@amgaynor The predicate in #57 seems broad enough to accommodate bibliographic and audio-visual usage of Series Title in the UHDL.

**Comment by metaweidner** [comment]
Let's use a table for the examples instead of a bulleted list, something like:

Type | Example
-----|-----
Book Series | [example book series title]
Television Series | [example television series title]
Video Series | [example video series title]

**Comment by amgaynor** [comment]
I've added the table as you suggested.
