### ISSUE TITLE
Update Format/Medium/Extent Guidelines

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#33]
In our last meeting we were trying to determine how best to map Genre, Physical Description and Extent. I've created a sheet in the DMWG that contains those fields for all objects in the digital library.

https://docs.google.com/spreadsheets/d/18FbGH7jZMjF84_KGYU0e9JT3-Q4AraNPWLTtRy_js4M/edit#gid=904342543

I've included notes some of the column headers. 

My thoughts right now would be to keep genre as it is, have our physical description map to DPLA format capturing the medium of the item, and then move number of pages and/or dimensions to extent. 

When migrating PhysDesc to Format, we could remove data that doesn't add add'l description, e.g. for letter, we do not need to include "document", and we could add number of pages to extent.

**Comment by metaweidner** [comment]
That mapping works for me @amgaynor 
Genre = Genre (Cedar AAT vocabulary)
PhysDesc = Format (medium of item)
PhysDesc/OrigItemExtent = Extent (quantity)

**Comment by metaweidner** [comment]
@amgaynor  New mappings and input rules based on decisions made in the 2017-02-16 DMWG meeting:

- Extent: quantitative information about the object (# pages, dimensions, etc.)
- Medium ( previously Format #58 ): "ink on paper", "oil on wood", etc.
- Format ( previously Genre #59 ): Cedar AAT vocabulary term

**Comment by amgaynor** [comment]
We need to confirm the accepted input standards for extent: 

Examples: 
23 **pages**
24 x 19.5 **cm**
02:23:00
2.18 MB
5 x 7 **in** (vs. 5" x 7" or 5 x 7 inches)

**Comment by amgaynor** [comment]
We'll need to revisit values for Genre once DPLA publishes list of 30-50 terms they'll be using.
