### ISSUE TITLE
Update Time Period Guidelines

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#34]
Make clear that this is capturing aboutness.

**Comment by amgaynor** [comment]
Will we be using this field? Can we think of examples when this would be helpful? We will have the date field filled in for many objects...

**Comment by metaweidner** [comment]
This field is not widely used in the UHDL. We could create a local controlled vocabulary for this in Cedar based on the Special Collections collecting areas. If this is the path we choose, ideally we'd add a Time Period to every object in the repository as a sort of macro-facet.

**Comment by metaweidner** [comment]
We may not be using this field. Depends on whether or not we do #39
