### ISSUE TITLE
Place of Creation

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#35]
In our last meeting we talked about Place of Creation and I mentioned that upon Andy and my first review of that field it looks like it's used for Publisher information in most cases. Since this field could be valuable, but doesn't seem to fit into any of the current fields, we talked about whether we might use [bf:providerPlace](http://bibframe.org/vocab/providerPlace.html). Another option would be to include this information in the publisher field formatting it similar to RDA/MARC rules.

Here's a report for Place of Creation in UHDL: https://docs.google.com/spreadsheets/d/18FbGH7jZMjF84_KGYU0e9JT3-Q4AraNPWLTtRy_js4M/edit#gid=422123412

**Comment by metaweidner** [comment]
Let's hold off on this until we know what capabilities the system provides us for defining metadata. We may be able to map this to a predicate like bf:providerPlace in conjunction with Publisher #15

**Comment by metaweidner** [comment]
@amgaynor [bf:providerPlace](http://bibframe.org/vocab/providerPlace.html) is a BF 1.0 predicate that no longer exists in 2.0. Given the similarities between [bf:place](http://id.loc.gov/ontologies/bibframe.html#p_place) and our [Place](https://vocab.lib.uh.edu/bcdams-map#spatial) field, I'd rather avoid confusion and shelve `Place of Creation` until we can find a way to tie this tightly to `Publisher`.
