### ISSUE TITLE
Add DPLA-MAP input rules to guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#36]

**Comment by seanlw** [comment]
I'm interested in this and possibly having Brays do validation against these rules if possible.

**Comment by metaweidner** [comment]
Having the input rules in the guidelines document for each field should help us to formulate the guidelines text and choose appropriate examples.

**Comment by amgaynor** [comment]
I finished adding the usage guidelines from the DPLA MAP v4 to our BCDAMS MAP. Not sure if you want to keep this issue open to address the validation you mention.

**Comment by metaweidner** [comment]
@amgaynor Some field guidelines are missing the DPLA MAP Usage statement:

- https://uhlibraries-digital.github.io/bcdams-map/guidelines/title
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/publisher
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/language
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/subject
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/spatial
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/temporal
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/hasType
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/format
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/type
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/identifier
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/rights

I see that some of those have portions of the definition already in the guidelines text. Let's make the DPLA MAP definition clear by adding the exact statement with the **DPLA MAP v4 Usage:** text you added to the other fields.

**Comment by amgaynor** [comment]
@metaweidner  I forgot to hit "Sync" in my desktop client. They should all be there now.
