### ISSUE TITLE
Create Access Rights local vocabulary

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#38]
A local vocabulary that defines levels of access will be necessary to complete #10

**Comment by librarycard** [comment]
These are the categories that we came up with for levels of access:
- Individual
- Staff only
- On-campus (IP range?) (cougarnet not required)
- UH authentication (cougarnet ID)
- Public access

**Comment by metaweidner** [comment]
Current values:

- Individual
- Staff
- Campus
- Community
- Public

**Comment by metaweidner** [comment]
Closed with #10
