### ISSUE TITLE
Update Note guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#40]
https://uhlibraries-digital.github.io/bcdams-map/guidelines/note

**Comment by metaweidner** [comment]
@amgaynor @librarycard Does the Note field needs input guidelines for both the Access and Preservation contexts?

**Comment by amgaynor** [comment]
@librarycard I have updated the guidelines for Acesss. I'm not sure if there were other guidelines you wanted to add for the Preservation context.

**Comment by amgaynor** [comment]
@metaweidner Is there a particular reason that `Note` is not a repeatable field? We have an instance where we would like to make a note about the archives where the digitized material is from, and also make a note about an error in the periodical numbering. I'm not sure that it's ideal that both notes would be two sentences in a single `Note` field. cc: @librarycard @christinz

**Comment by metaweidner** [comment]
@amgaynor Note is now repeatable b3afb0d
