### ISSUE TITLE
Update Identifier guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#42]
https://uhlibraries-digital.github.io/bcdams-map/guidelines/identifier

**Comment by librarycard** [comment]
can we put OCLC number here?

**Comment by metaweidner** [comment]
@librarycard That seems reasonable. Do you anticipate any other types that we should include in the guidelines?

- ARK
- OCLC
- Call Number
- Location (a.k.a. Original Item Location)

**Comment by librarycard** [comment]
@metaweidner i think that should cover it -- i can't think of any others at the moment.

**Comment by amgaynor** [comment]
@metaweidner @librarycard is this also where we would put the accession number? If so, would we follow the format "1970-001, Box 5, Folder 20"?  If we did this, however, this particular identifier wouldn't be unique.

**Comment by metaweidner** [comment]
@amgaynor Uniqueness is not required. The accession number should be sufficient to make that construction useful as an identifier.

**Comment by amgaynor** [comment]
@metaweidner Ok sounds good. I think we talked about the possibility of Brays generating this field value based on the filename. Does that sound right?

**Comment by metaweidner** [comment]
Let's use a table for the identifier examples instead of a bulleted list, something like:

Type | Example
-----|-----
Call Number | [call number example]
OCLC Number | [oclc number example]
Archival Location | [archival location example]
ARK | [ark example]

**Comment by amgaynor** [comment]
I didn't have an example of a real digital object ARK, so I put a fake one in the documentation. I'll update that once we have some real digital object ARKs.

**Comment by librarycard** [comment]
add to preservation input guidelines: preservation package ark goes here
