### ISSUE TITLE
Update namespace URI

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/bcdams-map#49]
Update the current hard coded URI `https://uhlibraries-digital.github.io` and move it to something that can be configured in the `_config.yml` file. This will allow the map to be cloned and used by other institutions with different URI's.

**Comment by metaweidner** [comment]
@seanlw Breaking API changes in progress.

**Comment by seanlw** [comment]
@metaweidner Ok, I'll update the URL as well to start pointing to https://vocab.lib.uh.edu/bcdams-map/

**Comment by metaweidner** [comment]
@seanlw MAP API Changes:
- `guidelines_uri` to `guidelines`
- `same_as_uri` to `source`

**Comment by metaweidner** [comment]
@seanlw what do you think about removing `hidden` and using `visible` to take the place of multiple application API calls (`api/archival`, etc...):

```
visible:
  - brays: true
  - carpenters: false
```

**Comment by seanlw** [comment]
@metaweidner I really wouldn't recommend putting application specific variables in the MAP. If it really comes down to wanting to hide specific fields, then we should do so as a feature for that specific application.

**Comment by metaweidner** [comment]
@seanlw Should I remove `hidden` altogether?

Also, what is the purpose of the `/api/archival.json` call?

**Comment by seanlw** [comment]
@metaweidner I'll have to check about the `hidden` field. The purpose of `/api/archival.json` is more about being a filter than anything. It's still providing data, but the data itself isn't specific to a application.
