### ISSUE TITLE
Crosswalk ASpace Fields

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#5]

**Comment by metaweidner** [comment]
Add EAD/ASpace column to crosswalks

**Comment by metaweidner** [comment]
@rmrichardson @librarycard @lisacruces: I've added an EAD/ASpace column to the DPTF & DAMSTF crosswalk documents:
- https://github.com/uhlibraries-digital/bcdams-map/wiki/02-DPTF-Metadata#uhdl-crosswalk
- https://github.com/uhlibraries-digital/bcdams-map/wiki/03-DAMSTF-Metadata#uhdl-crosswalk

**Comment by librarycard** [comment]
For DPTF Crosswalk (collection-level data)
- Original Collection: archdesc > did > unittitle
- Repository: archdesc > did > repository
- Creator: archdesc > did > origination
- Date: archdesc > did > unitdate
- Description: archdesc > scopecontent
- Publisher: this field does not really exist, at least not at the collection level, for an archival collection
- Use & Reproduction: archdesc > userestrict
- Title: archdesc > did > unittitle (again?)

**Comment by metaweidner** [comment]
Thanks @librarycard. I've added the EAD mappings to the crosswalk. I split out the EAD/ASpace column into 'EAD (archdesc)' and 'Aspace.'

**Comment by metaweidner** [comment]
@librarycard @rmrichardson @lisacruces 
Can we consider this issue closed, or is there still work to be done on this with relation to the MAP?

**Comment by metaweidner** [comment]
@librarycard @lisacruces @rmrichardson Some notes from today's DMWG meeting to guide your investigations into how we might map harvested descriptive metadata from the ASpace API:

**General rules for configuration at the application level**
- Item level description:
-- Title
-- Date
- Folder level description:
-- Title + Item #
-- Date
- Additional fields require further investigation:
-- Description (Scope and Contents Note)
-- Inherited levels of data
