### ISSUE TITLE
Create 'Brays' API call

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#54]
- `hidden`
- `input`

**Comment by metaweidner** [comment]
@seanlw Created the Brays API call. Changed `hidden` to `visible`
f4394cf 

Let me know if there are any changes or additions to make.

**Comment by seanlw** [comment]
@metaweidner Everything looks good after the change. I'm going to hold off pushing changes in Brays for a few days incase we think of any more changes.

**Comment by metaweidner** [comment]
@seanlw sounds good. i'll hold off on #55 for a little bit.
