### ISSUE TITLE
Remove 'hidden' and 'input' from elements

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#55]

**Comment by metaweidner** [comment]
Do this after #54

**Comment by metaweidner** [comment]
@seanlw Will removing `hidden` and `input` break anything with the Carpenters applications? I plan to remove those fields from the `archival` and `carpenters` responses as part of this issue.

**Comment by seanlw** [comment]
@metaweidner It doesn't look like it will. Carpenters relies on `name` and `namespace`, so as long as you leave those alone, you're good.

**Comment by metaweidner** [comment]
d3d13a0
