### ISSUE TITLE
Change Series Title Predicate

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#57]
[bf.partOf](http://id.loc.gov/ontologies/bibframe.html#p_partOf)

**Comment by metaweidner** [comment]
@amgaynor How do these look?
- https://uhlibraries-digital.github.io/bcdams-map/#partOf
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/partOf

**Comment by amgaynor** [comment]
@metaweidner Looks good to me! I'll add a couple of examples to the guidelines.

**Comment by metaweidner** [comment]
closed with e792e2a & 955f6b5
