### ISSUE TITLE
Convey relationships between items

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#68]
@metaweidner and @librarycard: We talked today about how we might convey relationships between items. We discussed two relationships:
- a whole-part relationship (e.g. an individual Eiden Coll. photograph is from a particular scrapbook)
- a related-item relationship (a transcript in the DL is related to a video in Avalon)

I looked to find some possible predicates for these and found: 
- For whole-part: `dcterms.isPartOf` (http://dublincore.org/documents/dcmi-terms/#terms-isPartOf). This term refines `dc.relation`.
- For related items: `dcterms.relation` (http://dublincore.org/documents/dcmi-terms/#terms-relation)
Both expect non-literal values. 

For series, we are currently using `bf.partOf` (https://vocab.lib.uh.edu/bcdams-map#partOf), which has the same definition of `dcterms.isPartOf`, and expects a Work, Instance, or Item as input. Right now we are entering strings. We've used this mostly for KUHT videos, but it also shows up in the other collections.

I'll look into this more next week, but wanted to post some initial thoughts

**Comment by metaweidner** [comment]
Transferred to Trello.
