### ISSUE TITLE
Add Avalon mapping to Series Title/partOf

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/bcdams-map#69]
Add mapping to [Series Title](https://vocab.lib.uh.edu/bcdams-map/guidelines/partOf)/partOf. Should be similar to Collection/[`isPartOf` crosswalk](https://github.com/uhlibraries-digital/bcdams-map/blob/gh-pages/_data/elements/isPartOf.yml).

Use (I think):
```
avalon:
    label: "note"
type: "series title"
```

**Comment by metaweidner** [comment]
@amgaynor 8f41acd4
