### ISSUE TITLE
Update Rights Guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#9]
- https://uhlibraries-digital.github.io/bcdams-map/#rights
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/rights

**Comment by librarycard** [comment]
Is there going to be a separate field for RS.org code? Is this rights field just for the human-readable use & reproduction statement?

**Comment by metaweidner** [comment]
From what I gather, Hybox will inherit Rights behavior from Sufia, most likely importing URIs and displaying a human-readable label like here: https://scholarsphere.psu.edu/files/2z10wq29w

In most cases, the Rights data should be sufficient to indicate to users how they can reuse/reproduce the object. Any additional administrative information might go in the Note field: https://uhlibraries-digital.github.io/bcdams-map/#note

**Comment by amgaynor** [comment]
@metaweidner The RMWG has come up with the statements that we are using (though, given some recent information, there may be one additional statement. We need to discuss it further):

- In Copyright
- In Copyright - Copyright Owner Unlocatable or Unidentifiable
- Public Domain
- Rights Undetermined

These all have text to describe the statements: 

Public Domain: This item is in the public domain and may be used freely.

In Copyright: This item is protected by copyright. Copyright to this resource is held by the creator or current rights holder, and the resource is provided here for educational purposes. It may not be reproduced or distributed in any format without permission of the copyright owner. Users assume full responsibility for any infringement of copyright or related rights.

Rights Undetermined: This item may be protected by copyright. UH Libraries has been unable to make a conclusive determination as to the copyright status of the item. Users assume full responsibility for any infringement of copyright or related rights.

In Copyright -- Copyright Owner Unlocatable or Unidentifiable: This item is protected by copyright. Copyright to this resource is held by the creator or current rights holder; however, for this item, either (a) no rights-holder(s) have been identified or (b) one or more rights-holder(s) have been identified but none have been located. Users assume full responsibility for any infringement of copyright or related rights.

For right now, are we putting the statement in along with the explanatory text or is there another way that we are handling the rights statements and descriptions?

**Comment by metaweidner** [comment]
@amgaynor @librarycard I'd prefer to have the short form in the metadata. The long form explanation belongs on some kind of About page in the repository.

**Comment by metaweidner** [comment]
@amgaynor Are the RMWG statements mapped to a URI?

**Comment by amgaynor** [comment]
@metaweidner Yes, the corresponding URIs are:

Statement | URI
----|----
In Copyright| http://rightsstatements.org/vocab/InC/1.0/
In Copyright - Copyright Owner Unlocatable or Unidentifiable | http://rightsstatements.org/vocab/InC-RUU/1.0/
Rights Undetermined | http://rightsstatements.org/vocab/UND/1.0/

There's a question as to whether we are going to use Public Domain (Maybe: https://creativecommons.org/publicdomain/mark/1.0/) or No Copyright - United States (http://rightsstatements.org/vocab/NoC-US/1.0/), based on new information.

**Comment by librarycard** [comment]
@amgaynor My understanding from SAA's recent report is that the Public Domain Mark will apply in some cases, and No Copyright - United States will apply in others. I think we may need to revise our copyright decision matrix to include both. Hopefully we can use the SAA report and flowchart as a starting point.

@metaweidner I feel strongly that both the RS.org URI and the human-readable statement belong in the descriptive metadata. They serve different purposes -- the URI allows users to facet based on copyright status, while the human-readable statement allows them to understand if & how they can reuse an image while they're looking at the digital object. A couple institutions are taking this approach that I know of, like Illinois and Miami, and there may be more. Can we discuss this in a DMWG meeting?

**Comment by amgaynor** [comment]
Per our Oral Histories Additions project meeting, @librarycard, @metaweidner Need to add: 

Statement | URI
----|----
In Copyright - Educational Use Permitted | http://rightsstatements.org/vocab/InC-EDU/1.0/

**Comment by metaweidner** [comment]
Rights Statement | Local Rights Statement
-----|-----
[In Copyright](http://rightsstatements.org/vocab/InC/1.0/) | This item is protected by copyright. Copyright to this resource is held by the creator or current rights holder, and the resource is provided here for educational purposes. It may not be reproduced or distributed in any format without permission of the copyright owner. Users assume full responsibility for any infringement of copyright or related rights.
[In Copyright - Copyright Owner Unlocatable or Unidentifiable](http://rightsstatements.org/vocab/InC-RUU/1.0/) | This item is protected by copyright. Copyright to this resource is held by the creator or current rights holder; however, for this item, either (a) no rights-holder(s) have been identified or (b) one or more rights-holder(s) have been identified but none have been located. Users assume full responsibility for any infringement of copyright or related rights.
[In Copyright - Educational Use Permitted](http://rightsstatements.org/vocab/InC-EDU/1.0/) | [educational use local statement]
[No Copyright - United States](http://rightsstatements.org/vocab/NoC-US/1.0/) | [no copyright local statement]
[Public Domain](https://creativecommons.org/publicdomain/mark/1.0/) | This item is in the public domain and may be used freely.
[Rights Undetermined](http://rightsstatements.org/vocab/UND/1.0/) | This item may be protected by copyright. UH Libraries has been unable to make a conclusive determination as to the copyright status of the item. Users assume full responsibility for any infringement of copyright or related rights.

**Comment by metaweidner** [comment]
@librarycard @amgaynor What is the status of the rights statements, and can we put the above table in our guidelines to get it started?

**Comment by amgaynor** [comment]
This is the table I am putting into the guidelines:

Rights Statement |     Local Rights Statement      
-----------------|---------------------------------
[Public Domain](https://creativecommons.org/publicdomain/mark/1.0/) | This item is in the public domain and may be used freely.
[No Copyright - United States](http://rightsstatements.org/vocab/NoC-US/1.0/) | This item is in the public domain in the United States and may be used freely in the United States. The item may not be in the public domain under the copyright laws of other countries.
[In Copyright](http://rightsstatements.org/vocab/InC/1.0/) | This item is protected by copyright. Copyright to this resource is held by the creator or current rights holder, and the resource is provided here for educational purposes. It may not be reproduced or distributed in any format without permission of the copyright owner. Users assume full responsibility for any infringement of copyright or related rights.
[Rights Undetermined](http://rightsstatements.org/vocab/UND/1.0/) | This item may be protected by copyright. UH Libraries has been unable to make a conclusive determination as to the copyright status of the item. Users assume full responsibility for any infringement of copyright or related rights.
[In Copyright - Copyright Owner Unlocatable or Unidentifiable](http://rightsstatements.org/vocab/InC-RUU/1.0/) | This item is protected by copyright. Copyright to this resource is held by the creator or current rights holder; however, for this item, either (a) no rights-holder(s) have been identified or (b) one or more rights-holder(s) have been identified but none have been located. Users assume full responsibility for any infringement of copyright or related rights.
[In Copyright - Educational Use Permitted](http://rightsstatements.org/vocab/InC-EDU/1.0/) | This item is protected by copyright. Copyright to this resource is held by the creator or current rights holder; however, you are free to use this item for educational purposes without obtaining permission from the rights holder(s). For other uses, permission from the rights-holder(s) is required.
